Fix `install-program`: Wait for snap to finish seeding
Snap needs to seed itself into the system before it can perform any
operations, such as installing the snap core. If done too early it will
emit an error like this:

```
error: too early for operation, device not yet seeded or device model not acknowledged
```